services:
#    membre.example:
#        class: MembreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    event.jwt_created_listener:
        class:      MembreBundle\Event\JWTCreatedListener
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    event.jwt_decoded_listener:
        class: MembreBundle\Event\JWTDecodedListener
        arguments: [ '@request_stack' ]
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }

    event.jwt_authenticated_listener:
        class: MembreBundle\Event\JWTAuthenticatedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_authenticated, method: onJWTAuthenticated }

    event.authentication_success_listener:
        class: MembreBundle\Event\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }

    event.authentication_failure_listener:
        class: MembreBundle\Event\AuthenticationFailureListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_failure, method: onAuthenticationFailureResponse }

    event.jwt_invalid_listener:
        class: MembreBundle\Event\JWTInvalidListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_invalid, method: onJWTInvalid }

    event.jwt_invalid_listener:
        class: MembreBundle\Event\JWTNotFoundListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_not_found, method: onJWTNotFound }

    event.jwt_expired_listener:
        class: MembreBundle\Event\JWTExpiredListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_expired, method: onJWTExpired }
   
    user.mailer.rest:
        class: MembreBundle\Mailer\RestMailer
        public: false
        parent: fos_user.mailer.twig_swift
    
    membre.service:
        class: MembreBundle\Service\MembreService
        arguments: ['@lexik_jwt_authentication.encoder.default' , '@doctrine.orm.entity_manager']
        


