<?php

namespace AcheteurBundle\Repository;

/**
 * AcheteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcheteurRepository extends \Doctrine\ORM\EntityRepository
{
}
