<?php

namespace PackBundle\Repository;

/**
 * EncherirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncherirRepository extends \Doctrine\ORM\EntityRepository
{
}
