security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_ACHETEUR:    ROLE_ACHETEUR
        ROLE_VENDEUR:     ROLE_VENDEUR
        

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
      
        api_login:
            pattern:  ^/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /login
                require_previous_session: false
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure


        healthcheck:
            pattern: ^/ping$
            anonymous: true

        api_docs:
            pattern: ^/doc
            anonymous: true

        api_register:
            pattern: ^/register
            anonymous: true

        api_password_reset:
            pattern: ^/password/reset
            anonymous: true
     

    access_control:
            - { path: ^/ping,             role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/doc,              role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login$,           role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register$,        role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/password/reset,   role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/vendeur,  role: ROLE_ADMIN }
            - { path: ^/password/change,  role: IS_AUTHENTICATED_FULLY }
            - { path: ^/,                 role: IS_AUTHENTICATED_FULLY }