<?php

namespace ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByVendeur($id_vendeur){
        
        $em = $this->getEntityManager();
        $dql = "SELECT p FROM ProduitBundle:Produit p JOIN p.magasin m JOIN m.vendeur v WHERE v.id = :id_vendeur";
        $produits = $em->createQuery($dql)
                ->setParameter('id_vendeur', $id_vendeur)
                ->getResult();
        return $produits;
        
    }
}
